export default {

	collections: [{
		name:'test1',
		key: '9564',
		list:[{
			name: '纯文本',
			icon: 'file-text',
			isOpend: false,
			key: '9781',
			label: '',
			type: 'text',
			helpText: '',
			isRequired: false,
		},{
			name: '富文本',
			icon: 'copy',
			isOpend: false,
			key: '9782',
			label: '',
			type: 'textarea',
			helpText: 'ssssss',
			isRequired: false,
		},{
			name: '图片',
			icon: 'picture',
			isOpend: false,
			key: '9783',
			label: '',
			type: 'image',
			helpText: '',
			isRequired: false,
		},{
			name: '视频',
			icon: 'play-circle-o',
			isOpend: false,
			key: '9784',
			label: '',
			type: 'video',
			helpText: '',
			isRequired: false,
		},{
			name: '链接',
			icon: 'link',
			isOpend: false,
			key: '9785',
			label: '',
			type: 'link',
			helpText: '',
			isRequired: false,
		},{
			name: '电子邮件',
			icon: 'mail',
			isOpend: false,
			key: '9786',
			label: '',
			type: 'Email',
			helpText: '',
			isRequired: false,
		},{
			name: '电话号码',
			icon: 'phone',
			isOpend: false,
			key: '9787',
			label: '',
			type: 'phone',
			helpText: '',
			isRequired: false,
		},{
			name: '纯数字',
			icon: 'minus',
			isOpend: false,
			key: '9788',
			label: '',
			type: 'number',
			helpText: '',
			isRequired: false,
		},{
			name: '日历',
			icon: 'calendar',
			isOpend: false,
			key: '9789',
			label: '',
			type: 'date',
			helpText: '',
			isRequired: false,
		},{
			name: '开关',
			icon: 'sync',
			isOpend: false,
			key: '9790',
			label: '',
			type: 'switch',
			helpText: '',
			isRequired: false,
		},{
			name: '颜色',
			icon: 'filter',
			isOpend: false,
			key: '9790',
			label: '',
			type: 'color',
			helpText: '',
			isRequired: false,
		},{
			name: '下拉选项',
			icon: 'caret-down',
			isOpend: false,
			key: '9791',
			label: '',
			type: 'option',
			value: [
					'value1','value2'
				],
			helpText: '',
			isRequired: false,
		},{
			name: 'Reference',
			icon: 'database',
			isOpend: false,
			key: '9792',
			label: '',
			type: 'Reference',
			helpText: '',
			isRequired: false,
		},{
			name: 'Multi-Reference',
			icon: 'database',
			isOpend: false,
			key: '9793',
			label: '',
			type: 'Multi-Reference',
			helpText: '',
			isRequired: false,
		}]
	}]
}