var component = {
	controllersList:[
		//小程序头部
		{
			name:'头部',
			tag:'view',
			type:'view'
			baseClassName:'page__hd',
			attr:{},
			children:[]
		},
		//小程序主体
		{
			name:'主体',
			tag:'view',
			baseClassName:'page__bd',
			attr:{
				class:{
					type:'toggle',
					title:'留空',
					isClassName:true,
					value: ['page__bd_spacing'],
					_value:true,
				},
			},
			children:[]
		},
		//页面标题
		{
			name:'页面标题',
			tag:'view',
			baseClassName:'page__title',
			children:['标题'],
		},
		//页面详情
		{
			name:'页面详情',
			tag:'view',
			baseClassName:'page__desc',
			children:['详细描述'],
		},
		//文章
		{
			name:'文章',
			tag:'view',
			baseClassName:'weui-article',
			children:[
				//文章头部
				{
					name:'文章大标题',
					tag:'view',
					baseClassName:'weui-article__h1',
					children:['大标题'],
				},
				//文章主体
				{
					name:'文章主体',
					tag:'view',
					baseClassName:'weui-article__section',
					children:[
						{
							name:'章标题',
							tag:'view',
							baseClassName:'weui-article__title',
							children:['章标题']
						},
						//文章
						{
							name:'章主体',
							tag:'view',
							baseClassName:'weui-article__section',
							children:[
								//文章小标题
								{
									name:'小标题',
									tag:'view',
									baseClassName:'weui-article__h3',
									children:['1.1 节标题'],
								},
								//文章内容
								{
									name:'小标题',
									tag:'内容',
									baseClassName:'weui-article__p',
									children:[
										'文章内容',
										{
											name:'图片内容',
											tag:'image',
											baseClassName:'weui-article__img',
											attr:{
												src:{
													type:'input',
													title:'src',
													isClassName:false,
													_value:'../images/pic_article.png',
												},
												mode:{
													type:'input',
													title:'mode',
													isClassName:false,
													_value:'aspectFit'
												},
												_style:{
													type:'input',
													title:'样式',
													isClassName:false,
													_value:'height: 180px',
												}
											}
										}
									],
								},
							]
						}
					]
				},
			],
		},
		//按钮
		{
			name:'按钮',
			tag:'button',
			baseClassName:'weui-btn',
			attr:{
				type:{
					type:'select',
					title:'类型',
					isClassName:false,
					value:['primary','default','warn'],
					_value:'default',
				},
				disabled:{
					type:'toggle',
					title:'禁用',
					isClassName:false,
					_value:false,
				},
				class:{
					type:'toggle',
					title:'类',
					isClassName:false,
					value:['mini-btn'],
					_value:false,
				},
				plain:{
					type:'toggle',
					title:'扁平化',
					isClassName:false,
					_value:false,
				},
				size:{
					type:'toggle',
					title:'尺寸',
					isClassName:false,
					value:['mini-btn'],
					_value:false,
				},
			},
			children:[],
		},
		//模态框
		{
			name:'模态框',
			tag:'view',
			baseClassName:'',
			attr:{},
			children:[],
		},
		//flex布局
		{
			name:'Flex布局',
			tag:'view',
			baseClassName:'weui-flex',
			attr:{},
			children:[
				{
					name:'FLex框',
					tag:'view',
					baseClassName:'weui-flex__item',
					attr:{},
					children:[
						{
							name:'文字',
							tag:'view',
							baseClassName:'placeholder',
							attr:{},
							children:['weui'],
						}
					],
				},
			],
		},
		//页脚
		{
			name:'页脚',
			tag:'view',
			baseClassName:'weui-footer',
			attr:{},
			children:[
				{
					name:'底部文字',
					tag:'view',
					baseClassName:'weui-footer__text',
					attr:{},
					children:['Copyright © 2008-2016 weui.io'],
				},
				{
					name:'底部链接',
					tag:'view',
					baseClassName:'weui-footer__links',
					attr:{},
					children:[
						{
							name:'链接内容',
							tag:'navigator',
							baseClassName:'weui-footer__link',
							attr:{
								url:{
									type:'input',
									title:'utl',
									isClassName:false,
									_value:'',
								}
							},
							children:['底部链接'],
						}
					]
				}
			],
		},
		//画廊
		//九宫格
		{
			name:'九宫格',
			tag:'view',
			baseClassName:'weui-grids',
			attr:{},
			children:[
				{
					name:'格子',
					tag:'view',
					baseClassName:'',
					attr:{},
					children:[
						{
							{
								name:'格子',
								tag:'block',
								baseClassName:'',
								attr:{
									'wx:for-items':{
										type:'input',
										title:'for',
										isClassName:false,
										_value:'{{grids}}',
									},
									'wx:key':{
										type:'input',
										title:'key',
										isClassName:false,
										_value:'{{index}}',
									},
								},
								children:[
									{
										{
											name:'格子',
											tag:'navigator',
											baseClassName:'weui-grid',
											attr:{
												'url':{
													type:'input',
													title:'url',
													isClassName:false,
													_value:'{{grids}}',
												},
												'hover-class':{
													type:'input',
													title:'hover',
													isClassName:false,
													_value:'{{index}}',
												},
											},
											children:[
												{
													name:'格子图片',
													tag:'image',
													baseClassName:'weui-grid__icon',
													attr:{
														src:{
															type:'input',
															title:'src',
															isClassName:false,
															_value:'../images/icon_tabbar.png',
														},
													},
													children:[],
												},
												{
													name:'格子文字',
													tag:'view',
													baseClassName:'weui-grid__label',
													attr:{},
													children:['Grid']
												}
											],
										},
									}
								],
							}
						},
					],
				}
			],
		},
		//图标
		{
			name:'图标',
			tag:'icon',
			baseClassName:'',
			attr:{
				type:{
					type:'select',
					title:'类型',
					isClassName:false,
					value:['success', 'success_no_circle', 'info', 'warn', 'waiting', 'cancel', 'download', 'search', 'clear'],
					_value:'success',
				},
				size:{
					type:'input',
					title:'尺寸',
					isClassName:false,
					_value:'93',
				},
			},
			children:[],
		},
		//单选列表
		{
			name:'单选列表',
			tag:'view',
			baseClassName:'weui-cells weui-cells_after-title',
			attr:{},
			children:[
				{
					name:'单选列表',
					tag:'radio-group',
					baseClassName:'',
					attr:{
						bindchange:{
							type:'input',
							title:'变化',
							isClassName:false,
							_value:'radioChange',
						},
					},
					children:[
						{
							name:'标签',
							tag:'label',
							baseClassName:'weui-cell weui-check__label',
							attr:{
								'wx:for':{
									type:'input',
									title:'for',
									isClassName:false,
									_value:'{{radioItems}}',
								},
								'wx:key':{
									type:'input',
									title:'key',
									isClassName:false,
									_value:'{{item.value}}',
								},
							},
							children:[
								{
									name:'',
									tag:'radio',
									baseClassName:'weui-check',
									attr:{
										value:{
											type:'input',
											title:'值',
											isClassName:false,
											_value:'值',
										},
										checked:{
											type:'toggle',
											title:'checked',
											isClassName:false,
											_value:false,
										},
									},
									children:[],
								},
								{
									name:'名字',
									tag:'view',
									baseClassName:'weui-cell__bd',
									attr:{},
									children:['名字'],
								},
								{
									name:'',
									tag:'view',
									baseClassName:'weui-cell__ft weui-cell__ft_in-radio',
									attr:{},
									children:[
										{
											name:'图标',
											tag:'icon',
											baseClassName:'weui-icon-radio',
											attr:{
												type:{
													type:'select',
													title:'类型',
													isClassName:false,
													value:['success_no_circle'],
													_value:'success_no_circle',
												},
												size:{
													type:'input',
													title:'大小',
													isClassName:false,
													_value:'16',
												}
											},
											children:[],
										},
									],
								},
							],
						}

					],
				},
				{
					name:'添加更多',
					tag:'view',
					baseClassName:'weui-cell weui-cell_link',
					attr:{},
					children:[
						{
							name:'body',
							tag:'view',
							baseClassName:'weui-cell__bd',
							attr:{},
							children:['添加更多'],
						}
					],
				}
			],
		},
		//复选列表项
		{
			name:'复选列表项',
			tag:'checkbox-group',
			baseClassName:'',
			attr:{
				bindchange:{
					type:'input',
					title:'事件',
					isClassName:false,
					_value:'checkboxChange',
				}
			},
			children:[
				{
					name:'列表',
					tag:'label',
					baseClassName:'weui-cell weui-check__label',
					attr:{},
					children:[
						{
							name:'项',
							tag:'checkbox',
							baseClassName:'weui-check',
							attr:{
								value:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'值',
								},
								checked:{
									type:'toggle',
									title:'checked',
									isClassName:false,
									_value:false,
								},
							},
							children:[],
						},
						{
							name:'',
							tag:'view',
							baseClassName:'weui-cell__hd weui-check__hd_in-checkbox',
							attr:{},
							children:[
								{
									name:'图标',
									tag:'icon',
									baseClassName:'weui-icon-checkbox_circle',
									attr:{
										type:{
											type:'input',
											title:'类型',
											isClassName:false,
											_value:'circle',
										},
										size:{
											type:'input',
											title:'大小',
											isClassName:false,
											_value:'23',
										},
										'wx:if':{
											type:'input',
											title:'wx:if',
											isClassName:false,
											_value:'{{!item.checked}}',
										}
									},
									children:[],
								},
								{
									name:'图标',
									tag:'icon',
									baseClassName:'weui-icon-checkbox_success',
									attr:{
										type:{
											type:'input',
											title:'类型',
											isClassName:false,
											_value:'success',
										},
										size:{
											type:'input',
											title:'大小',
											isClassName:false,
											_value:'23',
										},
										'wx:if':{
											type:'input',
											title:'wx:if',
											isClassName:false,
											_value:'{{item.checked}}',
										}
									},
									children:[],
								},
							],
						},
						{
							name:'name',
							tag:'view',
							baseClassName:'weui-cell__bd',
							attr:{},
							children:['{{item.name}}'],
						},
					],
				},
			],
		},
		//表单
		{
			name:'',
			tag:'view',
			baseClassName:'',
			attr:{},
			children:[
			],
		},
		//表单报错
		{
			name:'表单报错',
			tag:'view',
			baseClassName:'weui-cell weui-cell_input weui-cell_warn',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__hd',
					attr:{},
					children:[
						{
							name:'',
							tag:'view',
							baseClassName:'weui-label',
							attr:{},
							children:['卡号'
							],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:[
						{
							name:'输入框',
							tag:'view',
							baseClassName:'weui-input',
							attr:{
								placeholder:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'请输入xxx',
								},
							},
							children:[],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__ft',
					attr:{},
					children:[
						{
							name:'图标',
							tag:'icon',
							attr:{
								type:{
									type:'input',
									title:'类型',
									isClassName:false,
									_value:'warn',
								},
								size:{
									type:'input',
									title:'大小',
									isClassName:false,
									_value:'23',
								},
								'color':{
									type:'input',
									title:'颜色',
									isClassName:false,
									_value:'#E64340',
								}
							},
							children:[],
						},
					],
				},
			],
		},
		//开关
		{
			name:'开关',
			tag:'view',
			baseClassName:'weui-cell weui-cell_switch',
			attr:{},
			children:[
				{
					name:'标题',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:['标题文字'
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__ft',
					attr:{},
					children:[
						{
							name:'',
							tag:'switch',
							baseClassName:'',
							attr:{
								checked:{
									type:'toggle',
									title:'checked',
									isClassName:false,
									_value:true
								}
							},
							children:[
							],
						},
					],
				},
			],
		},
		//文本框
		{
			name:'文本框',
			tag:'view',
			baseClassName:'weui-cell weui-cell_input',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:[
						{
							name:'',
							tag:'input',
							baseClassName:'weui-input',
							attr:{
								placeholder:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'请输入文本'
								}
							},
							children:[
							],
						},
					],
				},
			],
		},
		//文本域
		{
			name:'文本域',
			tag:'view',
			baseClassName:'weui-cell',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:[
						{
							name:'',
							tag:'textarea',
							baseClassName:'weui-textarea',
							attr:{
								placeholder:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'请输入文本'
								}
							},
							children:[
							],
						},
						{
							name:'',
							tag:'view',
							baseClassName:'weui-textarea-counter',
							attr:{},
							children:['0/200'
							],
						},
					],
				},
			],
		},
		//选择1
		{
			name:'选择',
			tag:'view',
			baseClassName:'weui-cell weui-cell_select',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__hd',
					attr:{},
					children:[
						{
							name:'',
							tag:'picker',
							baseClassName:'',
							attr:{
								bindchange:{
									type:'input',
									title:'事件',
									isClassName:false,
									_value:'bindCountryCodeChange',
								},
								value:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'{{countryCodeIndex}}',
								},
								range:{
									type:'input',
									title:'range',
									isClassName:false,
									_value:'{{countryCodes}}',
								},
							},
							children:[
								{
									name:'',
									tag:'view',
									baseClassName:'weui-select',
									attr:{},
									children:['{{countryCodes[countryCodeIndex]}}'],
								},
							],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd weui-cell__bd_in-select-before',
					attr:{},
					children:[
						{
							name:'',
							tag:'input',
							baseClassName:'weui-input',
							attr:{
								placeholder:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'请输入xxx'
								}
							},
							children:[
							],
						},
					],
				},
			],
		},
		//选择2
		{
			name:'选择',
			tag:'view',
			baseClassName:'weui-cell weui-cell_select',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:[
						{
							name:'',
							tag:'picker',
							baseClassName:'',
							attr:{
								bindchange:{
									type:'input',
									title:'事件',
									isClassName:false,
									_value:'bindAccountChange',
								},
								value:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'{{accountIndex}}',
								},
								range:{
									type:'input',
									title:'range',
									isClassName:false,
									_value:'{{accounts}}',
								},
							},
							children:[
								{
									name:'',
									tag:'view',
									baseClassName:'weui-select',
									attr:{},
									children:['{{accounts[accountIndex]}}'],
								},
							],
						},
					],
				},
			],
		},
		//选择3
		{
			name:'选择',
			tag:'view',
			baseClassName:'weui-cell weui-cell_select',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__hd weui-cell__hd_in-select-after',
					attr:{},
					children:[
						{
							name:'',
							tag:'view',
							baseClassName:'weui-label',
							attr:{},
							children:['国家/地区'],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:[
						{
							name:'',
							tag:'picker',
							baseClassName:'',
							attr:{
								bindchange:{
									type:'input',
									title:'事件',
									isClassName:false,
									_value:'bindCountryChange',
								},
								value:{
									type:'input',
									title:'值',
									isClassName:false,
									_value:'{{countryIndex}}',
								},
								range:{
									type:'input',
									title:'range',
									isClassName:false,
									_value:'{{countries}}',
								},
							},
							children:[
								{
									name:'',
									tag:'view',
									baseClassName:'weui-select weui-select_in-select-after',
									attr:{},
									children:['{{countries[countryIndex]}}'],
								},
							],
						},
					],
				},
			],
		},
		//带说明的列表项
		{
			name:'',
			tag:'view',
			baseClassName:'weui-cell',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:['标题文字'
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__ft',
					attr:{},
					children:['说明文字'
					],
				},
			],
		},
		//带图标说明的列表项
		{
			name:'',
			tag:'view',
			baseClassName:'weui-cell',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__hd',
					attr:{},
					children:[
						{
							name:'',
							tag:'image',
							baseClassName:'weui-cell__hd',
							attr:{
								src:{
									type:'input',
									title:'src',
									isClassName:false,
									_value:'',
								}
							},
							children:[],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:['标题文字'
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__ft',
					attr:{},
					children:['说明文字'
					],
				},
			],
		},
		//带跳转的列表项
		{
			name:'',
			tag:'navigator',
			baseClassName:'weui-cell weui-cell_access',
			attr:{
				url:{
					type:'input',
					title:'url',
					isClassName:false,
					_value:'',
				},
				'hover-class':{
					type:'input',
					title:'hover class',
					isClassName:false,
					_value:'weui-cell_active',
				},
			},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:['cell standard'
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__ft weui-cell__ft_in-access',
					attr:{},
					children:[],
				},
			],
		},
		//带说明、跳转的列表项
		{
			name:'',
			tag:'navigator',
			baseClassName:'weui-cell weui-cell_access',
			attr:{
				url:{
					type:'input',
					title:'url',
					isClassName:false,
					_value:'',
				},
				'hover-class':{
					type:'input',
					title:'hover class',
					isClassName:false,
					_value:'weui-cell_active',
				},
			},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:['cell standard'
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__ft weui-cell__ft_in-access',
					attr:{},
					children:[
						'说明文字'
					],
				},
			],
		},
		//带图标、说明、跳转的列表项
		{
			name:'列表',
			tag:'navigator',
			baseClassName:'weui-cell weui-cell_access',
			attr:{
				url:{
					type:'input',
					title:'url',
					isClassName:false,
					_value:'',
				},
				'hover-class':{
					type:'input',
					title:'hover class',
					isClassName:false,
					_value:'weui-cell_active',
				},
			},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__hd',
					attr:{},
					children:[
						{
							name:'',
							tag:'image',
							baseClassName:'weui-cell__bd',
							attr:{
								src:{
									type:'input',
									title:'url',
									isClassName:false,
									_value:'{{icon}}',
								},
							},
							children:[],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__bd',
					attr:{},
					children:['cell standard'
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-cell__ft weui-cell__ft_in-access',
					attr:{},
					children:[
						'说明文字'
					],
				},
			],
		},
		//加载更多
		{
			name:'加载更多',
			tag:'view',
			baseClassName:'weui-loadmore',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-loading',
					attr:{},
					children:[
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-loadmore__tips',
					attr:{},
					children:[
						'正在加载'
					],
				},
			],
		},
		//暂无数据
		{
			name:'暂无数据',
			tag:'view',
			baseClassName:'weui-loadmore weui-loadmore_line',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-loadmore__tips weui-loadmore__tips_in-line',
					attr:{},
					children:['暂无数据'
					],
				},
			],
		},
		//提示页面
		{
			name:'',
			tag:'view',
			baseClassName:'',
			attr:{},
			children:[],
		},
		//导航
		{
			name:'导航',
			tag:'view',
			baseClassName:'weui-tab',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-navbar',
					attr:{},
					children:[
						{
							name:'blcok',
							tag:'block',
							baseClassName:'',
							attr:{
								'wx:for-items':{
									type:'input',
									title:'for',
									isClassName:false,
									_value:'{{tabs}}',
								},
								'wx:key':{
									type:'input',
									title:'key',
									isClassName:false,
									_value:'{{index}}',
								},
							},
							children:[
								{
									name:'',
									tag:'view',
									baseClassName:'',
									attr:{},
									children:[
										{
											name:'',
											tag:'view',
											baseClassName:'weui-navbar__title',
											attr:{},
											children:['{{item}}'],
										},
									],
								},

							]
						},
					],
				},
				{
					name:'选项',
					tag:'view',
					baseClassName:'weui-tab__panel',
					attr:{},
					children:[
						{
							name:'选项',
							tag:'view',
							baseClassName:'weui-tab__content',
							attr:{
								hidden:{
									type:'input',
									title:'隐藏',
									isClassName:false,
									_value:'{{activeIndex != 0}}',
								}
							},
							children:[],
						},
					],
				},
			],
		},
		//面板
		//表单预览
		//进度条
		{
			name:'',
			tag:'view',
			baseClassName:'weui-progress',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-progress__bar',
					attr:{},
					children:[
						{
							name:'',
							tag:'progress',
							baseClassName:'',
							attr:{
								percent:{
									type:'input',
									title:'百分比',
									isClassName:false,
									_value:'10',
								},
								'stroke-width':{
									type:'input',
									title:'宽度',
									isClassName:false,
									_value:'3',
								},
							},
							children:[
							],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-progress__opr',
					attr:{},
					children:[
						{
							name:'',
							tag:'icon',
							baseClassName:'',
							attr:{
								type:{
									type:'input',
									title:'类型',
									isClassName:false,
									_value:'cancel',
								},
								size:{
									type:'input',
									title:'尺寸',
									isClassName:false,
									_value:'22',
								},
							},
							children:[],
						},
					],
				}
			],
		},
		//搜索
		{
			name:'',
			tag:'view',
			baseClassName:'weui-search-bar',
			attr:{},
			children:[
				{
					name:'',
					tag:'view',
					baseClassName:'weui-search-bar__form',
					attr:{},
					children:[
						{
							name:'',
							tag:'view',
							baseClassName:'weui-search-bar__box',
							attr:{},
							children:[
								{
									name:'',
									tag:'icon',
									baseClassName:'weui-icon-search_in-box',
									attr:{
										type:{
											type:'input',
											title:'类型',
											isClassName:false,
											_value:'search',
										},
										size:{
											type:'input',
											title:'尺寸',
											isClassName:false,
											_value:'14',
										},
									},
									children:[],
								},
								{
									name:'',
									tag:'input',
									baseClassName:'weui-search-bar__input',
									attr:{
										type:{
											type:'input',
											title:'类型',
											isClassName:false,
											_value:'text',
										},
										placeholder:{
											type:'input',
											title:'placeholder',
											isClassName:false,
											_value:'搜索',
										},
										value:{
											type:'input',
											title:'文本',
											isClassName:false,
											_value:'{{inputVal}}',
										},
										focus:{
											type:'input',
											title:'事件',
											isClassName:false,
											_value:'{{inputShowed}}',
										},
										bindinput:{
											type:'input',
											title:'事件',
											isClassName:false,
											_value:'inputTyping',
										},
										bindblur:{
											type:'input',
											title:'事件',
											isClassName:false,
											_value:'hideInput',
										},
									},
									children:[],
								},
								{
									name:'',
									tag:'view',
									baseClassName:'weui-icon-clear',
									attr:{
										'wx:if':{
											type:'input',
											title:'事件',
											isClassName:false,
											_value:'{{inputVal.length > 0}}',
										},
										bindtap:{
											type:'input',
											title:'事件',
											isClassName:false,
											_value:'clearInput',
										},
									},
									children:[
										{
											name:'',
											tag:'icon',
											baseClassName:'',
											attr:{
												type:{
													type:'input',
													title:'类型',
													isClassName:false,
													_value:'clear',
												},
												size:{
													type:'input',
													title:'尺寸',
													isClassName:false,
													_value:'14',
												},
											},
											children:[],
										},
									],
								},
							],
						},
						{
							name:'',
							tag:'label',
							baseClassName:'weui-search-bar__label',
							attr:{
								hidden:{
									type:'toggle',
									title:'隐藏',
									isClassName:false,
									_value:false,
								},
								bindtap:{
									type:'input',
									title:'事件',
									isClassName:false,
									_value:'showInput',
								},
							},
							children:[
								{
									name:'图标',
									tag:'icon',
									baseClassName:'weui-icon-search',
									attr:{
										type:{
											type:'select',
											title:'类型',
											isClassName:false,
											value:['success', 'success_no_circle', 'info', 'warn', 'waiting', 'cancel', 'download', 'search', 'clear'],
											_value:'search',
										},
										size:{
											type:'input',
											title:'尺寸',
											isClassName:false,
											_value:'14',
										},
									},
									children:[],
								},
								{
									name:'',
									tag:'view',
									baseClassName:'weui-search-bar__text',
									attr:{},
									children:['搜索'],
								}
							],
						},
					],
				},
				{
					name:'',
					tag:'view',
					baseClassName:'weui-search-bar__cancel-btn',
					attr:{
						hidden:{
							type:'toggle',
							title:'隐藏',
							isClassName:false,
							_value:false,
						},
						bindtap:{
							type:'input',
							title:'事件',
							isClassName:false,
							_value:'hideInput',
						}
					},
					children:['取消'],
				},

			],
		},
		//实时搜索结果
		{
			name:'',
			tag:'view',
			baseClassName:'weui-cells searchbar-result',
			attr:{
				'wx:if':{
					type:'input',
					title:'wx:if',
					isClassName:false,
					_value:'{{inputVal.length > 0}}',
				}
			},
			children:[
				{
					name:'',
					tag:'navigator',
					baseClassName:'weui-cell',
					attr:{
						url:{
							type:'input',
							title:'url',
							isClassName:false,
							_value:'',
						},
						'hover-class':{
							type:'input',
							title:'hover-class',
							isClassName:false,
							_value:'weui-cell_active',
						},
					},
					children:[
						{
							name:'',
							tag:'view',
							baseClassName:'"weui-cell__bd',
							attr:{},
							children:[
								{
									name:'',
									tag:'view',
									baseClassName:'',
									attr:{},
									children:['实时搜索文本'],
								},
							],
						},
					],
				},
			],
		},
		//弹出式提示
		{
			name:'',
			tag:'view',
			baseClassName:'',
			attr:{},
			children:[],
		},
		//上传文件
		{
			name:'',
			tag:'view',
			baseClassName:'',
			attr:{},
			children:[],
		},


	]

}